### ISSUE TITLE
Broken Pipe error during Ping Pong

### ISSUE THREAD

**Issue by jmhummel** [faceshiftlabs/DeepFaceLab#18]
Experienced while using ping pong
```
Starting. Press "Enter" to stop training and save model.
[21:25:31][#181424][0468ms][bs: 2][2.9218][1.8652]]
[21:40:43][#182638][0562ms][bs: 3][2.5325][0.9613]
[21:55:57][#184068][0750ms][bs: 5][2.6892][1.1011]
[22:11:12][#185465][0468ms][bs: 2][2.6015][1.0453]
Error: [Errno 32] Broken pipes: 4][2.2346][0.9522]
Traceback (most recent call last):
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\mainscripts\Trainer.py", line 107, in trainerThread
    iter, iter_time, batch_size = model.train_one_iter()
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\models\ModelBase.py", line 534, in train_one_iter
    sample = self.generate_next_sample()
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\models\ModelBase.py", line 525, in generate_next_sample
    return [next(generator) for generator in self.generator_list]
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\models\ModelBase.py", line 525, in <listcomp>
    return [next(generator) for generator in self.generator_list]
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 66, in __next__
    return next(generator)
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\utils\iter_utils.py", line 62, in __next__
    self.p.start()
  File "multiprocessing\process.py", line 105, in start
  File "multiprocessing\context.py", line 223, in _Popen
  File "multiprocessing\context.py", line 322, in _Popen
  File "multiprocessing\popen_spawn_win32.py", line 65, in __init__
  File "multiprocessing\reduction.py", line 60, in dump
BrokenPipeError: [Errno 32] Broken pipe
Done.
Press any key to continue . . .
```

**Comment by jmhummel** [comment]
@ShumptonLang

**Comment by jmhummel** [comment]
This isn't the root error, since the error happened on a different process
here's the actual error:
```
    from skimage.feature import canny
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\python-3.6.8\lib\site-packages\skimage\feature\__init__.py", line 9, in <module>
    from .peak import peak_local_max
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\python-3.6.8\lib\site-packages\skimage\feature\peak.py", line 3, in <module>
    from ..segmentation import relabel_sequential
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\python-3.6.8\lib\site-packages\skimage\segmentation\__init__.py", line 3, in <module>
    from ._felzenszwalb import felzenszwalb
  File "D:\DeepFaceLabCUDA10.1AVX\_internal\python-3.6.8\lib\site-packages\skimage\segmentation\_felzenszwalb.py", line 3, in <module>
    from ._felzenszwalb_cy import _felzenszwalb_cython
ImportError: DLL load failed: The paging file is too small for this operation to complete.
```

**Comment by jmhummel** [comment]
![image](https://user-images.githubusercontent.com/1432270/63064826-21182080-beb8-11e9-92cc-8cc57d1b79d2.png)
It's starting a separate process for each batch_size change, that's why it can run out of memory

**Comment by camjac251** [comment]
I too faced a similiar issue on the latest master as of today

```batch
Running trainer.

Loading model...
Press enter in 2 seconds to override model settings.
Enable autobackup? (y/n ?:help skip:y) :
y
Write preview history? (y/n ?:help skip:y) :
y
Choose image for the preview history? (y/n skip:n) : y
Target iteration (skip:unlimited/default) :
0
Batch_size (?:help skip:16) :
16
Enable ping-pong? (y/n ?:help skip:True) :
y
Ping-pong iteration (skip:1000/default) :
1000
Feed faces to network sorted by yaw? (y/n ?:help skip:y):
y
Flip faces randomly? (y/n ?:help skip:y) : n
Optimizer mode? ( 1,2,3 ?:help skip:1) :
1
Use pixel loss? (y/n, ?:help skip: n ) :
n
Face style power ( 0.0 .. 100.0 ?:help skip:0.00) :
0.0
Background style power ( 0.0 .. 100.0 ?:help skip:0.00) :
0.0
Apply random color transfer to src faceset? (0) None, (1) LCT, (2) RCT, (3) RCT-c, (4) RCT-p, (5) RCT-pc, (6) mRTC, (7) mRTC-c, (8) mRTC-p, (9) mRTC-pc ?:help skip:0) :
0
Enable gradient clipping? (y/n, ?:help skip:y) :
y
Using TensorFlow backend.
Loading: 100%|####################################################################| 4435/4435 [00:13<00:00, 336.38it/s]
Sorting: 100%|########################################################################| 64/64 [00:00<00:00, 511.95it/s]
Loading: 100%|######################################################################| 961/961 [00:01<00:00, 660.48it/s]
Sorting: 100%|#######################################################################| 64/64 [00:00<00:00, 2509.85it/s]
===== Model summary =====
== Model name: SAE
==
== Current iteration: 4380
==
== Model options:
== |== autobackup : True
== |== write_preview_history : True
== |== batch_cap : 16
== |== ping_pong : True
== |== paddle : ping
== |== ping_pong_iter : 1000
== |== sort_by_yaw : True
== |== random_flip : False
== |== resolution : 128
== |== face_type : f
== |== learn_mask : True
== |== optimizer_mode : 1
== |== archi : liae
== |== ae_dims : 512
== |== e_ch_dims : 42
== |== d_ch_dims : 21
== |== multiscale_decoder : True
== |== ca_weights : True
== |== pixel_loss : False
== |== face_style_power : 0.0
== |== bg_style_power : 0.0
== |== apply_random_ct : 0
== |== clipgrad : True
== |== batch_size : 5
== Running on:
== |== [0 : Quadro P5000]
=========================
Starting. Press "Enter" to stop training and save model.
[00:59:16][#004933][1575ms][bs: 5][3.1995][3.5266]
[01:14:29][#005451][1665ms][bs: 6][2.3996][2.6720]
[01:29:41][#005977][1687ms][bs: 6][2.1454][2.3159]
[01:44:53][#006468][1780ms][bs: 7][1.9212][2.0899]
[02:00:10][#006968][1736ms][bs: 7][1.8200][1.9403]
[02:15:23][#007433][1878ms][bs: 8][1.6725][1.7949]
[02:30:35][#007906][1886ms][bs: 8][1.5761][1.7115]
[02:45:46][#008356][1934ms][bs: 9][1.5075][1.6089]
[03:01:02][#008813][1927ms][bs: 9][1.4411][1.5343]
[03:16:14][#009250][2007ms][bs: 10][1.4025][1.4515]
[03:31:27][#009690][2003ms][bs: 10][1.3411][1.3923]
[03:46:39][#010113][2097ms][bs: 11][1.2935][1.3460]
[04:01:57][#010531][2090ms][bs: 11][1.2350][1.2954]
[04:17:10][#010949][2122ms][bs: 11][1.2040][1.2551]
[04:32:23][#011345][2187ms][bs: 12][1.1730][1.2009]
[04:47:36][#011749][2190ms][bs: 12][1.1378][1.1630]
[05:02:54][#012137][2286ms][bs: 13][1.1105][1.1477]
[05:18:06][#012523][2317ms][bs: 13][1.0851][1.0905]
[05:33:20][#012910][2281ms][bs: 13][1.0489][1.0849]
Error: [Errno 32] Broken pipes: 14][1.0803][1.0437]
Traceback (most recent call last):
  File "C:\Users\User\Documents\df\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\mainscripts\Trainer.py", line 107, in trainerThread
    iter, iter_time, batch_size = model.train_one_iter()
  File "C:\Users\User\Documents\df\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\models\ModelBase.py", line 533, in train_one_iter
    sample = self.generate_next_sample()
  File "C:\Users\User\Documents\df\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\models\ModelBase.py", line 524, in generate_next_sample
    return [ generator.generate_next() for generator in self.generator_list]
  File "C:\Users\User\Documents\df\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\models\ModelBase.py", line 524, in <listcomp>
    return [ generator.generate_next() for generator in self.generator_list]
  File "C:\Users\User\Documents\df\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\samplelib\SampleGeneratorBase.py", line 25, in generate_next
    self.last_generation = next(self)
  File "C:\Users\User\Documents\df\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\samplelib\SampleGeneratorFace.py", line 67, in __next__
    return next(generator)
  File "C:\Users\User\Documents\df\DeepFaceLabCUDA9.2SSE\_internal\DeepFaceLab\utils\iter_utils.py", line 62, in __next__
    self.p.start()
  File "multiprocessing\process.py", line 105, in start
  File "multiprocessing\context.py", line 223, in _Popen
  File "multiprocessing\context.py", line 322, in _Popen
  File "multiprocessing\popen_spawn_win32.py", line 65, in __init__
  File "multiprocessing\reduction.py", line 60, in dump
BrokenPipeError: [Errno 32] Broken pipe
Done.
Press any key to continue . . .
```

**Comment by jmhummel** [comment]
@camjac251 Are you also seeing many python processes building up in the task manager?
