### ISSUE TITLE
Error: No module named 'samplelib.SamplegeneratorPingPong')

### ISSUE THREAD

**Issue by malebuffy** [faceshiftlabs/DeepFaceLab#79]
I get this error when I try to convert SAE with a model trained with DFL_Colab (deepshiftlab branch). I am using the prebuild Windows app from this branch.

> Loading model...
> Error: No module named 'samplelib.SampleGeneratorPingPong'
> Traceback (most recent call last):
>   File "F:\DEEP FAKES\DeepFaceLabOpenCLSSE - GNTM\_internal\DeepFaceLab\mainscripts\Converter.py", line 609, in main
>     model = models.import_model( args['model_name'])(model_path, device_args=device_args, training_data_src_path=training_data_src_path)
>   File "F:\DEEP FAKES\DeepFaceLabOpenCLSSE - GNTM\_internal\DeepFaceLab\models\ModelBase.py", line 69, in __init__
>     model_data = pickle.loads ( self.model_data_path.read_bytes() )
> ModuleNotFoundError: No module named 'samplelib.SampleGeneratorPingPong'
> Done.

**Comment by malebuffy** [comment]
Didn't extract correctly, case closed.
